### ISSUE TITLE
My slidebar menu box is off by 8px leaving a white strip down side

### ISSUE THREAD

**Issue by johnpanz** [adchsm/Slidebars#182] opened 2015-06-17 03:59 UTC
Every time a go to a new page, and open the mobile menu, it's off by 8px.

There is a disconnect, between the transform: translate(407px) value, and the margin-left:399px value that pushes the menu out.

Once I open and close the menu, it's fine, and works perfectly, anyone have any ideas?

**Comment by adchsm** [comment] 2015-06-17 07:33
I have heard of others having this issue, but I can't seem to replicate it. What OS and browser are you using? Are you using 0.10.3 or the new dev version?

**Comment by simboonlong** [comment] 2015-07-08 08:47
Hi there,

The issue is happening when using the Slidebar overlay animation in 0.010.3. The demo page is experiencing this problem too, try clicking the button on top right. http://plugins.adchsm.me/slidebars/

Upon digging around, It seems that Jquery didn't get the correct Slidebar width when the initial css display is none. Try commenting out this property in slidebars.css to see the effect:
Line 87  .sb-slidebar { display: none; }

Read up more at: http://stackoverflow.com/questions/1472303/jquery-get-width-of-element-when-not-visible-display-none

Use the above technique and put a getRealCssWidth() function somewhere in slider.js. Then replace at:
Line 119, 120

$left.css( 'marginLeft', '-' + $left.css( 'width' ) );
change to
$left.css( 'marginLeft', '-' + getRealCssWidth( $left ) );

Hope this helps.

**Comment by adchsm** [comment] 2015-07-16 07:42
Thanks for letting me know, I'll see if i can incorporate this into the new Slidebars 2.

**Comment by adchsm** [comment] 2016-07-02 10:20
This doesn't appear to happen in the new Slidebars. I'll close this, but feel free to open another issue if you continue to experience problems.

Thanks

Adam

**Closed by adchsm** 2016-07-02 10:20 UTC
